Patch 1
js-tasks-ru/jsbasic-20200727_bagov-marat pull request #1
Opened 2020-07-31 00:13 UTC by BagyBug

2020-07-31 00:22 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-07-31 22:34 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Первая задача
+ 1+1=2
```

Добавляю преподавателя (@stas-dolgachov) для код-ревью, посмотрим что он скажет :)

2020-08-01 01:19 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
Первая задача
+ 1+1=2
```
```diff
Вычислить факториал
- факториал 0 равен 1
- факториал 5 равен 120 
- факториал 3 равен 6 
- факториал 1 равен 1
```

2020-08-01 09:24 UTC, dolgachio submitted a review, later dismissed

2020-08-01 09:24 UTC, jsru commented
PR не может быть принят, обратитесь, пожалуйста, к преподавателю.

2020-08-01 09:26 UTC, dolgachio requested changes
В связи с тем, что вы добавили две задачи, вам нужно решить их обе, что pull request засчитался.

2020-08-01 21:35 UTC, jsru commented
@stas-dolgachov ping :)

2020-08-02 13:33 UTC, dolgachio requested changes

2020-08-02 13:33 UTC, stas-dolgachov commented on 1-module/1-task/index.js
> +const check = factorial(5);
Удалите, пожалуйста, эту строчку

2020-08-03 15:38 UTC, BagyBug commented
Объясните, пожалуйста, я не должен был создавать эту ветку Patch-1? Правильно задумывалось, что все работают в своем форке Master?
у меня все модули удалились из локалки. я выгрузил через консоль и подгрузился мастер весь

2020-08-14 07:42 UTC, merged